/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/prefectures': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPrefectures']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/population/composition/perYear': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPopulation']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    PrefectureResponse: {
      messages: string
      result: {
        prefCode: number
        prefName: string
      }[]
    }
    PopulationResponse: {
      messages: string
      result: {
        boundaryYear: number
        data: {
          /** @enum {string} */
          label: '総人口' | '年少人口' | '生産年齢人口' | '老年人口'
          data: {
            year: number
            value: number
          }[]
        }[]
      }
    }
    /** @enum {string} */
    BadRequestResponse: '400'
    ForbiddenResponse: {
      /** @enum {string} */
      statusCode: '403'
      message: string
      description: string
    }
    NotFoundResponse:
      | '404'
      | {
          /** @enum {string} */
          statusCode: '404'
          message: string
          description: string
        }
  }
  responses: {
    /** @description TooManyRequestsResponse */
    TooManyRequestsResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          message: string
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getPrefectures: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 指定された都道府県に関する都道府県データを取得する。 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json':
            | components['schemas']['PrefectureResponse']
            | components['schemas']['BadRequestResponse']
            | components['schemas']['ForbiddenResponse']
            | components['schemas']['NotFoundResponse']
        }
      }
      429: components['responses']['TooManyRequestsResponse']
    }
  }
  getPopulation: {
    parameters: {
      query: {
        prefCode: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 地域単位、年単位の年齢構成のデータを取得する。 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json':
            | components['schemas']['PopulationResponse']
            | components['schemas']['BadRequestResponse']
            | components['schemas']['ForbiddenResponse']
            | components['schemas']['NotFoundResponse']
        }
      }
      429: components['responses']['TooManyRequestsResponse']
    }
  }
}
