openapi: '3.0.3'
info:
  version: 1.0.0
  title: RESAS
  license:
    name: MIT
servers:
  - url: https://opendata.resas-portal.go.jp
paths:
  /api/v1/prefectures:
    get:
      operationId: getPrefectures
      tags:
        - common
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: 指定された都道府県に関する都道府県データを取得する。
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PrefectureResponse'
                  - $ref: '#/components/schemas/BadRequestResponse'
                  - $ref: '#/components/schemas/ForbiddenResponse'
                  - $ref: '#/components/schemas/NotFoundResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /api/v1/population/composition/perYear:
    get:
      operationId: getPopulation
      parameters:
        - in: query
          name: prefCode
          required: true
          schema:
            type: number
      tags:
        - common
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: 地域単位、年単位の年齢構成のデータを取得する。
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PopulationResponse'
                  - $ref: '#/components/schemas/BadRequestResponse'
                  - $ref: '#/components/schemas/ForbiddenResponse'
                  - $ref: '#/components/schemas/NotFoundResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
components:
  responses:
    TooManyRequestsResponse:
      description: TooManyRequestsResponse
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
  schemas:
    PrefectureResponse:
      type: object
      required:
        - messages
        - result
      properties:
        messages:
          type: string
        result:
          type: array
          items:
            type: object
            required:
              - prefCode
              - prefName
            properties:
              prefCode:
                type: integer
              prefName:
                type: string
    PopulationResponse:
      type: object
      required:
        - messages
        - result
      properties:
        messages:
          type: string
        result:
          type: object
          required:
            - boundaryYear
            - data
          properties:
            boundaryYear:
              type: integer
            data:
              type: array
              items:
                type: object
                required:
                  - label
                  - data
                properties:
                  label:
                    type: string
                    enum:
                      - 総人口
                      - 年少人口
                      - 生産年齢人口
                      - 老年人口
                  data:
                    type: array
                    items:
                      type: object
                      required:
                        - year
                        - value
                      properties:
                        year:
                          type: integer
                        value:
                          type: integer
    BadRequestResponse:
      type: string
      enum:
        - '400'
    ForbiddenResponse:
      type: object
      required:
        - statusCode
        - message
        - description
      properties:
        statusCode:
          type: string
          enum:
            - '403'
        message:
          type: string
        description:
          type: string
    NotFoundResponse:
      oneOf:
        - type: string
          enum:
            - '404'
        - type: object
          required:
            - statusCode
            - message
            - description
          properties:
            statusCode:
              type: string
              enum:
                - '404'
            message:
              type: string
            description:
              type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
