name: Code check
on:
  pull_request:
    branches: ['*']
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Check code
        run: pnpm run lint
      - name: Format check
        run: pnpm run format:check
